# Наукові бібліотеки Пайтона

[джерело](https://stxnext.com/blog/2018/09/20/most-popular-python-scientific-libraries/)

Головними з яких будуть(посортовані по пріоритету):

+ [NumPy](https://numpy.org/)
+ [matplotlib](https://matplotlib.org/)
+ [SciPy](https://www.scipy.org/)
+ [Pandas](https://pandas.pydata.org/)
+ [pytest](https://docs.pytest.org/en/latest/)
+ [IPython](https://ipython.org/)

Додаткові:

+ [Keras](http://keras.io/)
+ [SymPy](https://www.sympy.org/)
+ [Cirq](https://github.com/quantumlib/Cirq)
+ [TensorFlow](https://www.tensorflow.org/)

## NumPy

In [1]:
import numpy as np

In [5]:
a = np.arange(15).reshape(3, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [6]:
a.shape

(3, 5)

In [7]:
a.ndim

2

In [8]:
a.size

15

In [10]:
a.dtype.name

'int32'

In [11]:
a.itemsize

4

In [12]:
a.data

In [22]:
b = np.array([(1.5,2,3), (4,5,6)])
b

array([[1.5, 2. , 3. ],
       [4. , 5. , 6. ]])

In [18]:
b.ndim

2

In [19]:
np.empty((4,4))

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        8.45597329e-307],
       [2.22523004e-307, 1.69118108e-306, 8.01094494e-307,
        3.56043054e-307],
       [1.37961641e-306, 6.23048521e-307, 8.06638080e-308,
        8.01106038e-307],
       [6.89805151e-307, 1.78020169e-306, 1.42410974e-306,
        1.33504432e-306]])

In [21]:
np.arange(10, 30, 5)

array([10, 15, 20, 25])

Оскільки крок може бути `float` то в загальному важко передбачити кінцеву кількість едементів, а тому краще вжити `linspace`:

In [24]:
np.linspace( 0, 2, 9)

array([0.  , 0.25, 0.5 , 0.75, 1.  , 1.25, 1.5 , 1.75, 2.  ])